version: '3.4'

services:
  dind:
    image: docker-registry.wayproyect.com/dind
    container_name: wayproyect_dind
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - '22:22'